main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('desc/', views.desc, name='desc'),
    path('data/', views.data, name='data'),
    path('like/', views.Like, name='Like'),
    path('book/', views.Book, name='Book'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

main/views.py
import json
import re
from django.shortcuts import render
from pip._vendor import requests
from django.http.response import JsonResponse

def home(request):
    response = requests.get("http://www.omdbapi.com/?i=tt3896198&apikey=c80fffae").json()
    return render(request, 'main/home.html', {'response':response})

def desc(request):
    response = requests.get("http://www.omdbapi.com/?i=tt3896198&apikey=c80fffae").json()
    return render(request,'main/desc.html', {'response':response})

def data(request):
    response = requests.get("http://www.omdbapi.com/?i=tt3896198&apikey=c80fffae").json()
    url=request.GET['q']
    if not re.search(url, response['Title'], flags=re.IGNORECASE):
        response = 'Not Found'
    data=response
    return JsonResponse(data,safe=False)

def Like(request):
    response = requests.get("http://www.omdbapi.com/?i=tt3896198&apikey=c80fffae").json()
    return render(request,'main/Like.html', {'response':response})

def Book(request):
    response = requests.get("http://www.omdbapi.com/?i=tt3896198&apikey=c80fffae").json()
    return render(request,'main/Book.html', {'response':response})

main/templates/main/Book.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Movie List</title>
{% endblock meta %}

{% block content %}
  <div class="body">
  {% if response != "No Like Yet" %}
    <div class="movie_card" id="bright">
        <div class="info_section">
        <div class="movie_header">
            <img class="locandina" src="{{response.Poster}}"/>
            <h1>{{response.Title}}</h1>
            <h4>{{response.Released}}, {{response.Director}}</h4>
            <span class="minutes">{{response.Runtime}}</span>
            <p class="type">{{response.Genre}}</p>
        </div>
        <div class="movie_desc">
            <p class="text">{{response.Plot}}</p>
            <a href="{% url 'main:desc' %}" class="btn" style="background-color:#630000; color: white"><b>See Detail</b></a>
        </div>
        </div>
        <div class="blur_back bright_back"></div>
    </div>
  {% else %}
    <h1>No Like Yet</h1>
  {% endif %}
  </div>
{% endblock content %}

main/templates/main/Like.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Movie List</title>
{% endblock meta %}

{% block content %}
  <div class="body">
  {% if response != "No Like Yet" %}
    <div class="movie_card" id="bright">
        <div class="info_section">
        <div class="movie_header">
            <img class="locandina" src="{{response.Poster}}"/>
            <h1>{{response.Title}}</h1>
            <h4>{{response.Released}}, {{response.Director}}</h4>
            <span class="minutes">{{response.Runtime}}</span>
            <p class="type">{{response.Genre}}</p>
        </div>
        <div class="movie_desc">
            <p class="text">{{response.Plot}}</p>
            <a href="{% url 'main:desc' %}" class="btn" style="background-color:#630000; color: white"><b>See Detail</b></a>
        </div>
        </div>
        <div class="blur_back bright_back"></div>
    </div>
  {% else %}
    <h1>No Like Yet</h1>
  {% endif %}
  </div>
{% endblock content %}

main/templates/main/desc.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Movie Description</title>
{% endblock meta %}

{% block content %}
    <div class="description">
    </div>
    <div class="container">
    <div class="row">
        <div class="col-md-auto">
        <img src="{{response.Poster}}" alt="poster" width="200" height="300">
        </div>
        <div class="col">
        <h1 style="color: white;"><b>{{response.Title}}</b></h1>
        <h3 style="color: white;"><b>{{response.Released}}, {{response.Director}}</b></h3>
        <h4 style="color: white;"><b>{{response.Language}}, {{response.Country}}</b></h4>
        <h5 style="color: white;">{{response.Plot}}</h5>
        <h5 style="color: white;"><b>Genre:</b> {{response.Genre}}</h5>
        <p></p>
        <a style="color: white;"><b>Ratings:</b><br></a>
        {% for i in response.Ratings %}
          <a style="color: white;">{{i.Source}}: {{i.Value}}<br></a>
        {% endfor %}
        <p></p>
        <p style="color: white;"><b>Writers:</b> {{response.Writer}}</p>
        <p style="color: white;"><b>Actors:</b> {{response.Actors}}</p>
        <p style="color: white;"><b>Production:</b> {{response.Production}}</p>
        <p style="color: white;"><b>Box Office:</b> {{response.BoxOffice}}</p>
        <a href="{% url 'main:home' %}" class="btn" style="background-color:#630000; color: white"><b>Back</b></a>
        </div>
    </div>
    </div>
<script type="text/javascript">

</script>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Movie List</title>
{% endblock meta %}

{% block content %}
  <input id="keyword" class="form-control" placeholder="Search Movie Title">
  <div class="body">
  <div class="movie_card" id="bright">
    <div class="info_section">
      <div class="movie_header">
        <img class="locandina" src="{{response.Poster}}"/>
        <h1>{{response.Title}}</h1>
        <h4>{{response.Released}}, {{response.Director}}</h4>
        <span class="minutes">{{response.Runtime}}</span>
        <p class="type">{{response.Genre}}</p>
      </div>
      <div class="movie_desc">
        <p class="text">{{response.Plot}}</p>
        <a href="{% url 'main:desc' %}" class="btn" style="background-color:#630000; color: white"><b>See Detail</b></a>
      </div>
            
      <div class="movie_social" style="padding-top: 10px">
        <ul>
        <li id="love"><a href="{% url 'main:Like' %}" style="color:white;"><i onclick="likes()" class="icon-heart-empty"></i></a></li>
        <li id="book"><a href="{% url 'main:Book' %}" style="color:white;"><i onclick="books()" class="icon-bookmark-empty"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="blur_back bright_back"></div>
  </div>
  </div>

<script type="text/javascript">

    
    $("#keyword").keyup(function(){
        var inp = $("#keyword").val();
        $.ajax({
            url: '/data/'+'?q='+inp,
            success:function(data) {
                var array_items = data;
                var love = $("#love i").attr("class");
                var book = $("#book i").attr("class");
                $(".body").empty();
                if (array_items=="Not Found") {
                  $(".body").append("<img src=\"{% static 'img/not-found.png' %}\" alt=\"My image\" class=\"center\">");
                }
                else {
                  $(".body").append("<div class=\"movie_card\" id=\"bright\">" +
                                          "<div class=\"info_section\">" +
                                          "<div class=\"movie_header\">" +
                                            "<img class=\"locandina\" src=\"{{response.Poster}}\">" +
                                            "<h1>{{response.Title}}</h1>" +
                                            "<h4>{{response.Released}}, {{response.Director}}</h4>" +
                                            "<span class=\"minutes\">{{response.Runtime}}</span>" +
                                            "<p class=\"type\">{{response.Genre}}</p>" +
                                          "</div>" +
                                          "<div class=\"movie_desc\">" +
                                            "<p class=\"text\">{{response.Plot}}</p>" +
                                            "<a href=\"{% url 'main:desc' %}\" class=\"btn\" style=\"background-color:#630000; color: white\"><b>See Detail</b></a>" +
                                          "</div>" +
                                          "<div class=\"movie_social\" style=\"padding-top: 10px\">" +
                                            "<ul>" +
                                              "<li id=\"love\"><a href=\"{% url 'main:Like' %}\" style=\"color:white;\"><i onclick=\"likes()\" class=\""+love+"\"></i></a></li>" +
                                              "<li id=\"book\"><a href=\"{% url 'main:Book' %}\" style=\"color:white;\"><i onclick=\"books()\" class=\""+book+"\"></i></a></li>" +
                                            "</ul>" +
                                          "</div>" +
                                        "</div>" +
                                        "<div class=\"blur_back bright_back\"></div>");
                }
            }
        });
    });

    function likes() {
      $("#love i").toggleClass("icon-heart-empty icon-heart");
    }  

    function books() {
      $("#book i").toggleClass("icon-bookmark-empty icon-bookmark");
    }  

    function getCookie(cname) {
      var name = cname + "=";
      var decodedCookie = decodeURIComponent(document.cookie);
      var ca = decodedCookie.split(';');
      for(var i = 0; i <ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) == ' ') {
          c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
          return c.substring(name.length, c.length);
        }
      }
      return "";
    }
      
</script>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#630000;">
    <a class="navbar-brand" href="{% url 'main:home' %}"><b>Fadhl</b><b style="color: black;">Movie</b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:home' %}" style="color:#eeebdd;">Movie List <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:Like' %}" style="color:#eeebdd;">Liked <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:Book' %}" style="color:#eeebdd;">Bookmarked <span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
  </nav>

  {% block content %}
  {% endblock content %}
</body>

</html>